### PR TITLE
Added USER_TWEETS resource type

### PR DESCRIPTION
**Pull request by omarcinkonis**
Added USER_TWEETS resource type. Also added some fixes to generate the dist folder correctly using yarn.

### CODE REVIEW

**Comment by Rishikant181** [comment]
@omarcinkonis I think a better name for this resource is USER_TIMELINE since this also includes the retweets of the user as well. What do you think?

**Comment by omarcinkonis** [comment]
I used the name USER_TWEETS to match the Twitter GraphQL endpoint, see: https://github.com/Rishikant181/Rettiwt-Core/pull/74/files#diff-f0ea936845931a0e7c9cc42b6c412b7e68f59d63744dc0d6d4d78058eea643ef

I think it is best to keep the names consistent in order to avoid confusion. No need to reinvent anything.

That said, it is my opinion only. If you want the name changed, I will change it. Let me know

**Comment by Rishikant181** [comment]
@omarcinkonis That's a fair point.

I'll be reviewing it and potentially merging it in the evening. I'm afk now :)

**Comment by omarcinkonis** [comment]
Once reviewed, let me know if you want to have the naming 'timeline' or 'tweets' in rettiwt-api. I think it is better to keep consistency here, but in the API it might make sense to call it timeline. Maybe it will be easier to understand for the users of the package. But maybe we want consistency there as well. You decide.

Here are the api changes so far: https://github.com/Rishikant181/Rettiwt-API/compare/dev...omarcinkonis:Rettiwt-API:dev

**Comment by Rishikant181** [comment]
Sure will :)

**Comment by Rishikant181** [comment]
Upon further thought, I think it's better to use USER_TIMELINE since it's more user friendly. Making the naming scheme different in both API and Core might introduce more ambiguity, so I think it's better to stick to the user-friendly option for now.

**Comment by Rishikant181** [comment]
Okay we'll be sticking with USER_TWEETS. It's consistent with the existing nomenclature and with Twitter/X.

**Pull request merged**
